# Override sensitive values at install time, e.g.:
#   helm install django-app ./charts/django-app \
#     --set image.repository=<your-ecr-url> \
#     --set secret.postgresPassword=<your-password> \
#     --set secret.djangoSecretKey=<your-secret-key>
image:
  repository: "740948698725.dkr.ecr.us-west-2.amazonaws.com/final-project-ecr"
  tag: v1.0.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80           # external port exposed by the LoadBalancer
  containerPort: 8000 # internal port Django listens on

ingress:
  enabled: false

autoscaler:
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

secret:
  postgresPassword: "admin123AWS23"   # must match modules/rds password in main.tf
  djangoSecretKey: "CHANGE-ME-django-insecure-key"  # any random string works for the demo

config:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,.elb.amazonaws.com"
  POSTGRES_HOST: "myapp-db.cro6wuesev0n.us-west-2.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DB: myapp
